"use client"

import { useEffect, useState } from "react"
import DockShader from "../components/portfolio/dock-shader"

const profile = "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/unnamed%20%2811%29-5eM4LcXo9WshDgvNQdAkUCyvwGEgNt.jpg"
const brand = (slug: string) => `https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/${slug}/mono.svg`
const roles = [
  ["Founder & Product Lead", "Seedr", "2026 — Present", "Building an exclusive, high-signal network for relentless operators and founders to build the next big thing."],
  ["Product Management & Agentic AI", "IIT Patna", "2025", ""],
  ["AI Product Manager", "recruit.ai (Stealth)", "2025", "Architected an agentic workflow product in a rapid sprint, taking it from raw insight to a fully autonomous AI recruitment engine."],
]
const stack = [
  ["React Native", "react"], ["Supabase", "supabase"], ["Vercel", "vercel"], ["Expo", "expo"], ["Claude Code", "anthropic"], ["Grok", "xai"], ["Anti-gravity", "google"], ["n8n", "n8n"], ["LangChain", "langchain"], ["Figma", "figma"],
]
const products = [
  ["recruit.ai", "Agentic workflow automation built with n8n and custom LLM agents to streamline recruitment pipelines.", "2025", ["AI Agents", "Automation", "2025"]],
  ["Medical Ops Platform", "A robust operational platform engineered for seamless hospital data flow and high-stakes workflow integrity.", "2025", ["Healthcare", "Systems Design", "2025"]],
  ["Agentic Research Assistant", "An autonomous agent that plans, retrieves, and synthesizes multi-source data into structured, citable research briefs.", "2025", ["Agentic AI", "LLM Orchestration", "2025"]],
]

function Clock() { const [time, setTime] = useState(""); useEffect(() => { const tick = () => setTime(new Intl.DateTimeFormat("en-IN", { timeZone: "Asia/Kolkata", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false }).format(new Date()) + " IST"); tick(); const id = setInterval(tick, 1000); return () => clearInterval(id) }, []); return <span>{time}</span> }

function DockIcon({ name }: { name: "home" | "grid" | "linkedin" | "github" | "x" | "instagram" | "calendar" | "theme" }) { const paths = { home: "M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1V10Z", grid: "M4 4h5v5H4zM15 4h5v5h-5zM4 15h5v5H4zM15 15h5v5h-5z", linkedin: "M6 9v9M6 6.5v.01M10 18v-5a3 3 0 0 1 6 0v5M10 9v9", github: "M12 3a9 9 0 0 0-3 17.5c.5.1.7-.2.7-.5v-1.8c-2.8.6-3.4-1.2-3.4-1.2-.5-1.1-1.1-1.4-1.1-1.4-.9-.6.1-.6.1-.6 1 0 1.5 1 1.5 1 .9 1.5 2.4 1.1 3 .8.1-.6.3-1.1.6-1.3-2.2-.3-4.5-1.1-4.5-4.8 0-1.1.4-2 1-2.7-.1-.3-.4-1.3.1-2.7 0 0 .8-.3 2.8 1a9.5 9.5 0 0 1 5 0c2-1.3 2.8-1 2.8-1 .5 1.4.2 2.4.1 2.7.6.7 1 1.6 1 2.7 0 3.7-2.3 4.5-4.5 4.8.3.3.6.9.6 1.8V20c0 .3.2.6.7.5A9 9 0 0 0 12 3Z", x: "M5 4l14 16M19 4 5 20", instagram: "M7 3h10a4 4 0 0 1 4 4v10a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V7a4 4 0 0 1 4-4Zm5 5a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm5-1v.01", calendar: "M5 4h14a2 2 0 0 1 2 2v13H3V6a2 2 0 0 1 2-2Zm-2 5h18M8 2v4M16 2v4", theme: "M20 15.5A8 8 0 1 1 8.5 4 6 6 0 0 0 20 15.5Z" } as const; return <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d={paths[name]} /></svg> }
function BrandIcon({ slug, label }: { slug: string; label?: string }) { return <img src={brand(slug)} alt={label ?? ""} aria-hidden={!label} onError={(event) => { event.currentTarget.style.display = "none" }} /> }

export default function Home() {
  const [light, setLight] = useState(false)
  const [fullStack, setFullStack] = useState(false)
  return <main id="top" className={light ? "site light" : "site"}>
    <section className="hero"><div className="avatar-wrap"><img src={profile} alt="Krish Khanvilkar in a snowy mountain landscape" className="avatar" /><i /></div><h1>Krish Khanvilkar</h1><div className="clock"><b /> <Clock /></div><div className="bio"><p>I am an AI builder who falls in love with complex, real-world problems—not just the tech that solves them. I move relentlessly from raw insight to high-velocity prototypes, 0 to 1 executions, designing experiences that feel completely effortless on the surface while remaining deeply rigorous underneath. As AI rapidly evolves, I build right alongside it, architecting products where trust is earned and execution is absolute.</p></div></section>
    <div className="content">
      <section className="card experience"><header><label>PREVIOUSLY</label></header>{roles.map(([title, org, year, detail], i) => <details key={title} open={i === 0}><summary><span><strong>{title}</strong><small>{org}</small></span><em>{year}</em><b>⌄</b></summary>{detail && <div className="detail"><p>{detail}</p>{i === 0 && <ul><li>Defined the 0-to-1 product vision, go-to-market strategy, and core builder network mechanics.</li><li>Architected and shipped the full mobile engine using React Native, Supabase, and Expo.</li><li>Executed deep user discovery loops with early-stage operators to refine retention and platform value.</li></ul>}</div>}</details>)}</section>
      <section className="card stack" id="stack"><header><label>WHAT I BUILD WITH</label><button onClick={() => setFullStack(!fullStack)} aria-expanded={fullStack}>View Full Stack <span>{fullStack ? "⌃" : "⌄"}</span></button></header><div className={`marquee ${fullStack ? "expanded" : ""}`}><div className="marquee-track">{[...stack, ...stack].map(([name, slug], i) => <span key={`${name}-${i}`}><BrandIcon slug={slug} label={name} />{name}</span>)}</div></div>{fullStack && <div className="stack-more" aria-label="Full technology stack"><div><label>CORE ENGINE &amp; INFRASTRUCTURE</label>{stack.slice(0, 4).map(([name, slug]) => <span key={name}><BrandIcon slug={slug} label={name} />{name}</span>)}</div><div><label>DESIGN &amp; ARCHITECTURE</label>{[["Claude Code","anthropic"],["Grok","xai"],["LangChain","langchain"],["n8n","n8n"],["Anti-gravity","google"],["OpenAI","openai"],["Figma","figma"]].map(([name, slug]) => <span key={name}><BrandIcon slug={slug} label={name} />{name}</span>)}</div></div>}</section>
      <section className="card disciplines"><label>BEYOND THE STACK</label><h2>Product, UX, and AI</h2><p className="muted">The disciplines I bring to every team and every build.</p><div className="discipline-grid">{[["AI Product Strategy", "Designing products where autonomous agents execute complex, multi-step workflows."],["0-to-1 Execution", "Rapid technical prototyping. From whiteboard to clickable, functional build in days."],["Systems Architecture", "Structuring data layers, API integrations, and edge-synced databases."],["High-Signal UX", "Research-led interfaces designed to reduce cognitive load and handle non-deterministic AI outputs."]].map(([a,b]) => <div key={String(a)}><h3>• <span>{String(a)}</span></h3><p>{b}</p></div>)}</div></section>
      <section className="card flagship"><div className="eyebrow"><label>FLAGSHIP PRODUCT</label><span className="live"><i /> Live</span></div><div className="seedr-glow" aria-hidden="true" /><div className="seedr-brand"><img src="/favicon19.png" alt="Seedr logo" /><h2>Seedr</h2></div><p>The private network for relentless operators to build the next big thing.</p><div className="pills"><span>⌘ Built with React Native &amp; Supabase</span></div><div className="specs"><div><label>PLATFORM</label><b>React Native<br />Expo</b></div><div><label>BACKEND</label><b>Supabase</b></div><div><label>ROLE</label><b>Product Lead<br />&amp; Architect</b></div></div><a href="https://seedr-eta.vercel.app" target="_blank" rel="noreferrer">Visit Seedr ↗</a></section>
      <section className="products" id="products"><label>PRODUCTS SO FAR</label>{products.map(([name, desc, year, tags]) => <article className="card product" key={String(name)}><div><h3>{String(name)}</h3><p>{String(desc)}</p><div className="tags">{(tags as string[]).map(t => <span key={String(t)}>{String(t)}</span>)}</div></div><time>{year}</time></article>)}</section>
      <section className="education" id="education"><label>EDUCATION</label><div className="edu-row"><div><h3>Product Management &amp; Agentic AI</h3><p>IIT Patna</p></div><time>2025 — 2026</time></div><div className="edu-row"><div><h3>Bachelor of Management Studies</h3><p>Mumbai University</p></div><time>2023 — 2026</time></div><div className="edu-row"><div><h3>Project Management Essentials</h3><p>Howard University</p></div><time>2024</time></div><div className="edu-row"><div><h3>Google UX Design Professional Certificate</h3><p>Google</p></div><time>2023</time></div></section>
      <section className="card contact" id="contact"><label>GET IN TOUCH</label><h2>Let&apos;s build something<br />that matters</h2><p>Open to AI Product roles, technical founding teams, and conversations with fellow operators.</p><div className="contact-actions"><a className="primary" href="https://cal.com/krish-khanvilkar" target="_blank" rel="noreferrer">▣ &nbsp; Schedule a meeting</a><a href="mailto:khanvilkarkrish38@gmail.com">□ &nbsp; Email me</a></div><div className="social"><a href="https://linkedin.com/in/krishkhanvilkar" target="_blank" rel="noreferrer">in</a><a href="https://github.com" target="_blank" rel="noreferrer">◉</a><a href="https://x.com/thekrish__" target="_blank" rel="noreferrer">𝕏</a><a href="https://instagram.com/kr1sh.k_" target="_blank" rel="noreferrer">◎</a></div></section>
      <footer>© 2026 Krish Khanvilkar</footer>
    </div>
    <nav className="dock" aria-label="Quick navigation"><DockShader light={light} /><a href="#top" aria-label="Home"><DockIcon name="home" /></a><a href="#products" aria-label="Products"><DockIcon name="grid" /></a><a href="https://linkedin.com/in/krishkhanvilkar" target="_blank" rel="noreferrer" aria-label="LinkedIn"><DockIcon name="linkedin" /></a><a href="https://github.com" target="_blank" rel="noreferrer" aria-label="GitHub"><DockIcon name="github" /></a><a href="https://x.com/thekrish__" target="_blank" rel="noreferrer" aria-label="X"><DockIcon name="x" /></a><a href="https://instagram.com/kr1sh.k_" target="_blank" rel="noreferrer" aria-label="Instagram"><DockIcon name="instagram" /></a><a href="#education" aria-label="Education"><DockIcon name="calendar" /></a><button onClick={() => setLight(!light)} aria-label="Toggle light mode"><DockIcon name="theme" /></button></nav>
  </main>
}
